site_name: Jaseci
site_url: https://jaseci.org/
docs_dir: docs
use_directory_urls: true

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Inter

nav:
  - Home: index.md
  - Community: community.md
  - About Us: about-us.md
  - Blog: blog/index.md

plugins:
  - blog
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

  - open-in-new-tab

extra_css:
  - stylesheets/blog.css
  - stylesheets/navbar.css
  - stylesheets/landing.css
  - stylesheets/aboutus.css
  - stylesheets/community.css
  - stylesheets/layout.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/atom-one-dark.min.css

extra_javascript:
  - js/subscribe.js
  - js/landing.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js

extra:
  header_links:
    - label: Docs
      url: /
    - label: GitHub
      url: https://github.com/Jaseci-Labs/jaseci
      external: true
    - label: Contact
      url: mailto:hello@jaseci.org
      cta: true

hide:
  - navigation
  - toc
